version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: cardb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
